<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Rajesh-V" ignored="0" name="Test" tests="8" failures="2" timestamp="2021-12-28T14:26:34 IST" time="0.063" errors="0">
  <testcase name="credentials" time="0.012" classname="com.TestNg_Project.Retry_Demo">
    <skipped/>
  </testcase> <!-- credentials -->
  <testcase name="credentials" time="0.0" classname="com.TestNg_Project.Retry_Demo">
    <skipped/>
  </testcase> <!-- credentials -->
  <testcase name="credentials" time="0.0" classname="com.TestNg_Project.Retry_Demo">
    <skipped/>
  </testcase> <!-- credentials -->
  <testcase name="credentials" time="0.001" classname="com.TestNg_Project.Retry_Demo">
    <failure type="java.lang.AssertionError" message="expected [Tony Stark] but found [tony Stark]">
      <![CDATA[java.lang.AssertionError: expected [Tony Stark] but found [tony Stark]
at com.TestNg_Project.Retry_Demo.credentials(Retry_Demo.java:13)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- credentials -->
  <testcase name="credentials1" time="0.0" classname="com.TestNg_Project.Retry_Demo">
    <skipped/>
  </testcase> <!-- credentials1 -->
  <testcase name="credentials1" time="0.0" classname="com.TestNg_Project.Retry_Demo">
    <skipped/>
  </testcase> <!-- credentials1 -->
  <testcase name="credentials1" time="0.002" classname="com.TestNg_Project.Retry_Demo">
    <skipped/>
  </testcase> <!-- credentials1 -->
  <testcase name="credentials1" time="0.0" classname="com.TestNg_Project.Retry_Demo">
    <failure type="java.lang.AssertionError" message="expected [Peter123] but found [TonyStark12]">
      <![CDATA[java.lang.AssertionError: expected [Peter123] but found [TonyStark12]
at com.TestNg_Project.Retry_Demo.credentials1(Retry_Demo.java:21)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- credentials1 -->
</testsuite> <!-- Test -->
